CREATE TABLE Usuarios (
IdUsuario INT IDENTITY PRIMARY KEY,
Servicio NVARCHAR(100) NOT NULL,
Email NVARCHAR(150) NOT NULL UNIQUE,
PasswordHash NVARCHAR(255),
Rol NVARCHAR(50),
Activo BIT DEFAULT 1,
FechaCreacionUsuario DATETIME DEFAULT GETDATE()
);